### ISSUE TITLE
SyntaxError: invalid identity escape in regular expression - Firefox

### ISSUE THREAD

**Issue by aronnebrivio** [Marketto/diacritic-remover#14]
**Environment:**
- Browser name and version/Node version: Firefox 74

**Platform**
[ ] nodeJs
[x] Web/Browser

**Issue description:**
On js load it throws an error on Firefox:
`SyntaxError: invalid identity escape in regular expression`

On Chrome it's working well.

This is because Firefox does not support Unicode Property Escapes yet (an ES2018 feature), like `\p{M}`.

**Comment by Marketto** [comment]
It seems to be a bug of Firefox, bugfix will be released on v.76
https://bugzilla.mozilla.org/show_bug.cgi?id=1620020

Since marker removal is a feature of the library, I'll release a version with a fix which disable this regex on unsupported environments
