### ISSUE TITLE
React demo is broken on Firefox

### ISSUE THREAD

**Issue by ale-rinaldi** [Marketto/diacritic-remover#8]
**Environment:**
- OS: Ubuntu 19.10
- Browser name and version/Node version: Firefox 73.0

**Platform**
[ ] nodeJs
[X] Web/Browser

**Issue description:**
On Firefox 73.0 the React demo does not run:
```
SyntaxError: invalid identity escape in regular expression
DiacriticAbstractHandler
node_modules/@marketto/diacritic-remover/dist/diacritic-remover.mjs:18
```
Maybe other demos and the library itself is affected by the issue; I tried only the React demo and using the library inside a React project.

**Steps to reproduce the problem**:
1. Go to the React demo
2. npm install
3. npm start
4. Go to http://localhost:3000 on Firefox

**Expected behavior**
The demo runs

**Screenshots**
The demo does not run

**Comment by Marketto** [comment]
It seems to be a bug of Firefox, bugfix will be released on v.76
https://bugzilla.mozilla.org/show_bug.cgi?id=1620020

Since marker removal is a feature of the library, I'll release a version with a fix which disable this regex on unsupported environments

**Comment by agos** [comment]
it's not really a bug rather a missing feature - Unicode property escapes (`\p`) are a new feature, introduced in ES2018 and not yet implemented on all browsers yet (IE11 and Edge also don't have it at the time of this comment)
